version: '3'

services:
  frontend:
    build: "./client/frontend.dockerfile"
    ports:
      - "80:8080"
    restart: always

  backend:
    build: "./server/backend.dockerfile"
    ports:
      - "5000:5000"
    restart: always

  database:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "datastore:/data/db"

  # database-inspector:
  #   image: mongoclient/mongoclient
  #   restart: always
  #   ports:
  #     - "3000:3000"
